apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-management-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-service
                port:
                  number: {{ .Values.app.port }}
    - host: {{ .Values.ingress.grafanaHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: {{ .Values.grafana.port }}
