# ============================================================
# ☸️ KUBERNETES SERVICE - MYSQL
# ============================================================

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      name: mysql
    - port: {{ .Values.mysql.exporter.port }}
      targetPort: {{ .Values.mysql.exporter.port }}
      name: metrics