# ============================================================
# ☸️ KUBERNETES DEPLOYMENT - MYSQL
# ============================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-tools
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: MYSQL_DATABASE
              value: "studentdb"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.15.1
          ports:
            - containerPort: 9104
              name: metrics
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: DATA_SOURCE_NAME
              value: "$(DB_USER):$(DB_PASS)@(localhost:3306)/"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc