# ============================================================
# ☸️ KUBERNETES SECRETS
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-tools
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "spring"
  SPRING_DATASOURCE_PASSWORD: "spring123"