# ============================================================
# ☸️ KUBERNETES SERVICE - SPRING APP
# ============================================================

apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: {{ .Values.namespace }}
  labels:
    app: spring-app
spec:
  selector:
    app: spring-app
  type: NodePort
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
      name: http