apiVersion: v1
kind: ConfigMap
metadata:
  name: student-management-config
  namespace: student-management
  labels:
    app.kubernetes.io/name: student-management
    app.kubernetes.io/managed-by: kubectl
data:
  SPRING_PROFILES_ACTIVE: "k8s,prod"
  SERVER_PORT: "8089"
  CONTEXT_PATH: "/student"
  CORS_ALLOWED_ORIGINS: "http://localhost:4200"
  API_SECURITY_ENABLED: "true"
  MYSQL_DATABASE: "studentdb"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
