# ============================================================
# ☸️ KUBERNETES SECRETS
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-tools
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root123"
  JWT_SECRET: "2Y3nT8qKp9RvS5wXaZbC7dEfGhIjKlMnOpQrStUvWx"
  MAIL_PASSWORD: "email_password123"