# ============================================================
# 🐳 DOCKER COMPOSE OVERRIDE - DEV
# ============================================================

services:
  spring-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_SHOW_SQL: "true"
      LOGGING_LEVEL_ROOT: DEBUG
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ../src:/app/src
    ports:
      - "8089:8089"
      - "5005:5005"
  mysql:
    ports:
      - "3307:3306"

