apiVersion: v1
kind: Secret
metadata:
  name: student-management-mysql-secret
  namespace: student-management
  labels:
    app.kubernetes.io/name: student-management
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  root-password: U3VwM3JTM2NyM3RSb290
  app-user: c3R1ZGVudF9hcHA=
  app-password: U3RVZDNudEFwcFBAc3Mh
---
apiVersion: v1
kind: Secret
metadata:
  name: student-management-app-secret
  namespace: student-management
  labels:
    app.kubernetes.io/name: student-management
    app.kubernetes.io/managed-by: kubectl
type: Opaque
data:
  actuator-user: b3BzX2FkbWlu
  actuator-password: T3BzQGRtaW5QQHNzIQ==
  api-user: YXBpX3VzZXI=
  api-password: QXBpVSRlclBAc3Mh
